### ISSUE TITLE
thoughts on templ?

### ISSUE THREAD

**Issue by mikelu92** [katabole/katabole#1]
what are your thoughts on [templ](https://templ.guide) a golang templating engine that enables a lot of quality of life things for go templates:

- first class lsp support that hooks into gopls for better code completion/syntax highlighting
- type safety in templates
- faster (allegedly) than raw go templates

**Comment by dankinder** [comment]
@mikelu92 would you have time to try submitting a PR to https://github.com/katabole/kbexample that uses templ instead of go templates/render? I'm open to the idea and that'd be the first thing needed anyway. Having that will help a lot.

**Comment by dankinder** [comment]
Closing per https://github.com/katabole/kbexample/pull/1
